apiVersion: v1
kind: Service
metadata:
  name: macine-learning-app
spec:
  selector:
    app: macine-learning-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
    nodePort: 30000
  type : LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macine-learning-app
spec:
  selector:
    matchLabels:
      app: macine-learning-app
  replicas: 3
  template:
    metadata:
      labels:
        app: macine-learning-app
    spec:
      containers:
      - name: macine-learning-app
        image: docker-ml
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: macine-learning-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: machine-learning-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name:  macine-learning-app
            port:
              number: 80